export const DISTRICT_LIST_LOADING = Symbol("DISTRICT_LIST_LOADING");
export const DISTRICT_LIST_SUCCESS = Symbol("DISTRICT_LIST_SUCCESS");
export const DISTRICT_LIST_FAILED = Symbol("DISTRICT_LIST_FAILED");

