export const DOCUMENT_UPLOAD_LOADING = Symbol("DOCUMENT_UPLOAD_LOADING");
export const DOCUMENT_UPLOAD_SUCCESS = Symbol("DOCUMENT_UPLOAD_SUCCESS");
export const DOCUMENT_UPLOAD_FAILED = Symbol("DOCUMENT_UPLOAD_FAILED");
export const DOCUMENT_UPLOAD_DELETE_SUCCESS = Symbol("DOCUMENT_UPLOAD_DELETE_SUCCESS");
export const RESET_DOCUMENT_UPLOAD = Symbol("RESET_DOCUMENT_UPLOAD");

