export const METROPOLITAN_LIST_LOADING = Symbol("METROPOLITAN_LIST_LOADING");
export const METROPOLITAN_LIST_SUCCESS = Symbol("METROPOLITAN_LIST_SUCCESS");
export const METROPOLITAN_LIST_FAILED = Symbol("METROPOLITAN_LIST_FAILED");

