export const VEHICLE_ENTRIES_LOADING = Symbol(
  'VEHICLE_ENTRIES_LOADING',
);
export const VEHICLE_ENTRIES_SUCCESS = Symbol(
  'VEHICLE_ENTRIES_SUCCESS',
);
export const VEHICLE_ENTRIES_FAILED = Symbol(
  'VEHICLE_ENTRIES_SUCCESS',
);
export const VEHICLE_ENTRIES_UPDATE_LOADING = Symbol(
  'VEHICLE_ENTRIES_UPDATE_LOADING',
);
export const VEHICLE_ENTRIES_UPDATE_SUCCESS = Symbol(
  'VEHICLE_ENTRIES_UPDATE_SUCCESS',
);
export const VEHICLE_ENTRIES_UPDATE_FAILED = Symbol(
  'VEHICLE_ENTRIES_UPDATE_FAILED',
);
export const RESET_VEHICLE_ENTRIES = Symbol('RESET_VEHICLE_ENTRIES');

export const VEHICLE_ADD_ROW = Symbol('VEHICLE_ADD_ROW');
export const VEHICLE_REMOVE_ROW = Symbol('VEHICLE_REMOVE_ROW');
export const VEHICLE_EDIT_ROW = Symbol('VEHICLE_EDIT_ROW');

export const VEHICLE_BORDER_ENTRIES_LOADING = Symbol(
  'VEHICLE_BORDER_ENTRIES_LOADING',
);
export const VEHICLE_BORDER_ENTRIES_SUCCESS = Symbol(
  'VEHICLE_BORDER_ENTRIES_SUCCESS',
);
export const VEHICLE_BORDER_ENTRIES_FAILED = Symbol(
  'VEHICLE_BORDER_ENTRIES_SUCCESS',
);
